Query:
  type: object
  config:
    fields:
      getAllListings:
        type: "[Listing!]!"
        resolve: '@=resolver("App\\GraphQL\\Resolver\\ListingResolver::resolveListings")'
      getListingById:
        type: "Listing"
        args:
          id:
            description: "Listing ID"
            type: "Int"
        resolve: '@=resolver("App\\GraphQL\\Resolver\\ListingResolver::resolveListing", [args])'