listing_index:
  path:
    en: /list/all
  controller: App\UserInterface\Website\UseCase\Listing\ListingController::index
listing_show:
  path:
    en: /list/show/{id}
  controller: App\UserInterface\Website\UseCase\Listing\ListingController::show
listing_create:
  path:
    en: /list/create
  controller: App\UserInterface\Website\UseCase\Listing\ListingController::create
listing_edit:
  path:
    en: /list/edit/{id}
  controller: App\UserInterface\Website\UseCase\Listing\ListingController::edit
listing_delete:
  path:
    en: /list/delete/{id}
  controller: App\UserInterface\Website\UseCase\Listing\ListingController::delete
item_create:
  path:
    en: /list/show/{listing_id}/create_item
  controller: App\UserInterface\Website\UseCase\Item\ItemController::create