listing_index:
  path:
    en: /list/all
  controller: App\UserInterface\Website\Listing\ListingController::index
listing_create:
  path:
    en: /list/create
  controller: App\UserInterface\Website\Listing\ListingController::create
